name: core
description: Management of Cargo Ships Multiplatform.
version: 0.1.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  bloc: ^0.9.3
  equatable: ^0.1.0
  intl: ^0.15.7
  http: ^0.12.0
  meta: ^1.1.6

dev_dependencies:
  intl_translation: ^0.17.3