name: web
description: Web code for SeaTrack.
# version: 1.0.0
# homepage: https://www.example.com
# author: KingDarBoja <email@example.com>

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_bloc: ^0.4.1
  angular_components: ^0.11.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+21
  core:
    path: ../core

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.4.0
  test: ^1.5.1
